mywedding/myapp/urls.py
from django.urls import path,include
from . import views
app_name='myapp'
urlpatterns = [

  path('',views.index,name='index'),
  path('go/',views.go,name='go'),
  path('ex/',views.ex,name='ex'),
  path('<slug:c_slug>/',views.allyear,name='allyear'),
  #path('<slug:c_slug>/<slug:p_slug>/', views.proDetail, name='prodCatdetail'),

]

mywedding/mywedding/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),


]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mywedding/myapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Year(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
         return reverse('myapp:allyear',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    image = models.ImageField(upload_to='product', blank=True)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

  #  def get_url(self):
   #     return reverse('shop:prodCatdetail',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

mywedding/myapp/views.py
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Year,Product

# Create your views here.

def index(request):
    return render(request, 'index.html')

def go(request):
    return render(request, 'users.html')

def ex(request):
    return render(request, 'contests.html')

def allyear(request,c_slug=None):
    c_page=None
    product_list=None

    if c_slug!=None:
        c_page=get_object_or_404(Year,slug=c_slug)
        product_list=Product.objects.all().filter(year_id=c_page)
    else:
        product_list=Product.objects.all()

    paginator=Paginator(product_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'images.html',{'category':c_page,'products':products})

mywedding/templates/contest-details.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">

    <title>SnapX Photo Contest Detail</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="assets/css/fontawesome.css">
    <link rel="stylesheet" href="assets/css/templatemo-snapx-photography.css">
    <link rel="stylesheet" href="assets/css/owl.css">
    <link rel="stylesheet" href="assets/css/animate.css">
    <link rel="stylesheet"href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
<!--

TemplateMo 576 SnapX Photography

https://templatemo.com/tm-576-snapx-photography

-->
  </head>

<body>


  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky">
      <div class="container">
          <div class="row">
              <div class="col-12">
                  <nav class="main-nav">
                      <!-- ***** Logo Start ***** -->
                      <a href="index.html" class="logo">
                          <img src="assets/images/logo.png" alt="SnapX Photography Template">
                      </a>
                      <!-- ***** Logo End ***** -->
                      <!-- ***** Menu Start ***** -->
                      <ul class="nav">
                          <li><a href="index.html">Home</a></li>
                          <li class="has-sub">
                              <a href="javascript:void(0)" class="active">Photos &amp; Videos</a>
                              <ul class="sub-menu">
                                  <li><a href="contests.html">Contests</a></li>
                                  <li><a href="contest-details.html">Single Contest</a></li>
                              </ul>
                          </li>
                          <li><a href="categories.html">Categories</a></li>
                          <li><a href="users.html">Users</a></li>
                      </ul>   
                      <div class="border-button">
                        <a id="modal_trigger" href="#modal" class="sign-in-up"><i class="fa fa-user"></i> Sign In/Up</a>
                      </div>
                      <a class='menu-trigger'>
                          <span>Menu</span>
                      </a>
                      <!-- ***** Menu End ***** -->
                  </nav>
              </div>
          </div>
      </div>
  </header>
  <!-- ***** Header Area End ***** -->

  <div id="modal" class="popupContainer" style="display:none;">
    <div class="popupHeader">
        <span class="header_title">Login</span>
        <span class="modal_close"><i class="fa fa-times"></i></span>
    </div>

    <section class="popupBody">
        <!-- Social Login -->
        <div class="social_login">
            <div class="">
                <a href="#" class="social_box fb">
                    <span class="icon"><i class="fab fa-facebook"></i></span>
                    <span class="icon_title">Connect with Facebook</span>

                </a>

                <a href="#" class="social_box google">
                    <span class="icon"><i class="fab fa-google-plus"></i></span>
                    <span class="icon_title">Connect with Google</span>
                </a>
            </div>

            <div class="centeredText">
                <span>Or use your Email address</span>
            </div>

            <div class="action_btns">
                <div class="one_half"><a href="#" id="login_form" class="btn">Login</a></div>
                <div class="one_half last"><a href="#" id="register_form" class="btn">Sign up</a></div>
            </div>
        </div>

        <!-- Username & Password Login form -->
        <div class="user_login">
            <form action="" method="post">
                <label>Email / Username</label>
                <input name="username" type="text" id="username" />
              <br />

                <label>Password</label>
                <input name="password" type="password" id="password" />
              <br />

                <div class="checkbox">
                    <input id="remember" type="checkbox" />
                    <label for="remember">Remember me on this computer</label>
                </div>

                <div class="action_btns">
                    <div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
                    <div class="one_half last"><button type="submit" class="btn btn_red">Login</button></div>
                </div>
            </form>

            <a href="#" class="forgot_password">Forgot password?</a>
        </div>

        <!-- Register Form -->
        <div class="user_register">
            <form action="" method="post">
                <label>Username</label>
                <input name="username" type="text" id="username" />
                <br />

                <label>Email Address</label>
                <input name="email" type="email" id="email" />
                <br />

                <label>Password</label>
                <input name="password" type="password" id="password" />
                <br />

                <div class="checkbox">
                    <input id="send_updates" type="checkbox" />
                    <label for="send_updates">Send me occasional email updates</label>
                </div>

                <div class="action_btns">
                    <div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
                    <div class="one_half last"><button type="submit" class="btn btn_red">Register</button></div>
                </div>
            </form>
        </div>
        
    </section>
  </div>

  <div class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 offset-lg-2 header-text">
          <h2 class="space-need">A Walk In The Nature <em>Contest</em></h2>
          <h6>Contest Deadline</h6>
          <div class="main-content">
            <div class="counter">
              <div class="days">
                <div class="value">00</div>
                <span>Days</span>
              </div>
              <div class="hours">
                <div class="value">00</div>
                <span>Hours</span>
              </div>
              <div class="minutes">
                <div class="value">00</div>
                <span>Minutes</span>
              </div>
              <div class="seconds">
                <div class="value">00</div>
                <span>Seconds</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="contest-details">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="top-content">
            <div class="row">
              <div class="col-lg-4">
                <span class="open">Open Contest</span>
                <span class="wish-list"><i class="fa fa-heart"></i> Add To Your Favorites</span>
              </div>
              <div class="col-lg-8">
                <ul>
                  <li><i class="fa fa-medal"></i> <span>Award:</span> $2,400</li>
                  <li><span>Time left:</span> 7 Days</li>
                  <li><span>Participants:</span> 118</li>
                  <li><span>Submittions:</span> 280</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="main-content">
            <h4>Requirements Of The Contest</h4>
            <h6>Picture Should Have</h6>
            <p>SnapX Photography is a professional website template with 5 different HTML pages for maximum customizations. This is based on Bootstrap v5.1.3 CSS framework. Please visit TemplateMo website to see more CSS templates.</p>
            <p>You are allowed to 100% freely use this SnapX Template for your commercial websites. You are not allowed to redistribute the template ZIP file on any other Free CSS Template collection websites.</p>
            <h6 class="second-title">Picture Should Not Have</h6>
            <p>We hope this template is very useful for your website development. If you wish to <a rel="nofollow" href="https://templatemo.com/contact" target="_blank">support TemplateMo</a>, you may make a small amount of donation via PayPal.</p>
            <p>If you need the PSD source files of this template, please feel free to contact TemplateMo. Our supporters are welcome.</p>
            <h4 class="second-title">Links To Inspire Your Photo</h4>
            <div class="row">
              <div class="col-lg-3 col-6">
                <div class="item">
                  <span>JPG</span>
                  <h5>A Trip In The Rain<br><h6>Previous Winner</h6></h5>
                </div>
              </div>
              <div class="col-lg-3 col-6">
                <div class="item">
                  <span>PNG</span>
                  <h5>A Trip In The Jungle<br><h6>Previous Winner</h6></h5>
                </div>
              </div>
              <div class="col-lg-3 col-6">
                <div class="item">
                  <span>PDF</span>
                  <h5>A Trip In The Mountain<br><h6>Previous Winner</h6></h5>
                </div>
              </div>
              <div class="col-lg-3 col-6">
                <div class="item">
                  <span>AI</span>
                  <h5>A Trip In The Forest<br><h6>Previous Winner</h6></h5>
                </div>
              </div>
            </div>
            <div class="main-button">
              <a href="#">Submit Your Photo/Video</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <section class="contest-waiting">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h5>Other Contests Waiting For You:</h5>
        </div>
        <div class="col-lg-3 col-sm-6">
          <div class="waiting-item">
            <img src="assets/images/waiting-01.jpg" alt="">
            <div class="down-content">
              <h4>Best Mountain Picture Award</h4>
              <p>Lorem ipsum dolor siter and ametters conseietur adipiscing elit.</p>
              <span class="price">Price: <em>$900</em></span>
              <span class="deadline">Deadline: <em>3 Days</em></span>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-sm-6">
          <div class="waiting-item">
            <img src="assets/images/waiting-02.jpg" alt="">
            <div class="down-content">
              <h4>Nature Walk in the Forest</h4>
              <p>Lorem ipsum dolor siter and ametters conseietur adipiscing elit.</p>
              <span class="price">Price: <em>$1,400</em></span>
              <span class="deadline">Deadline: <em>2 Days</em></span>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-sm-6">
          <div class="waiting-item">
            <img src="assets/images/waiting-03.jpg" alt="">
            <div class="down-content">
              <h4>The Road to Photograph</h4>
              <p>Lorem ipsum dolor siter and ametters conseietur adipiscing elit.</p>
              <span class="price">Price: <em>$1,250</em></span>
              <span class="deadline">Deadline: <em>4 Days</em></span>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-sm-6">
          <div class="waiting-item">
            <img src="assets/images/waiting-04.jpg" alt="">
            <div class="down-content">
              <h4>The Lake and Mountain Scenery</h4>
              <p>Lorem ipsum dolor siter and ametters conseietur adipiscing elit.</p>
              <span class="price">Price: <em>$1,600</em></span>
              <span class="deadline">Deadline: <em>10 Days</em></span>
            </div>
          </div>
        </div>
        <div class="col-lg-12">
          <ul class="pagination">
            <li><a href="#"><i class="fa fa-arrow-left"></i></a></li>
            <li><a href="#">1</a></li>
            <li class="active"><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#"><i class="fa fa-arrow-right"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright © 2048 <a href="#">SnapX</a> Photo Contest Co., Ltd. All rights reserved. 
          
          Design: <a title="CSS Templates" rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a></p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

  <script src="assets/js/isotope.min.js"></script>
  <script src="assets/js/owl-carousel.js"></script>
  
  <script src="assets/js/tabs.js"></script>
  <script src="assets/js/popup.js"></script>
  <script src="assets/js/custom.js"></script>

  </body>
</html>

mywedding/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&amp;display=swap" rel="stylesheet">

    <title>SnapX Photography by TemplateMo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-snapx-photography.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css">
</head>
<body>

</body>
</html>

mywedding/templates/images.html
{% load static %}
<html lang="en"><head>
{% include 'header.html' %}
<!--

TemplateMo 576 SnapX Photography

https://templatemo.com/tm-576-snapx-photography

-->
  </head>

<body>

{% include 'nav.html' %}

  <div id="modal" class="popupContainer" style="display:none;">
    <div class="popupHeader">
        <span class="header_title">Login</span>
        <span class="modal_close"><i class="fa fa-times"></i></span>
    </div>

    <section class="popupBody">
        <!-- Social Login -->
        <div class="social_login">
            <div class="">
                <a href="#" class="social_box fb">
                    <span class="icon"><i class="fab fa-facebook"></i></span>
                    <span class="icon_title">Connect with Facebook</span>

                </a>

                <a href="#" class="social_box google">
                    <span class="icon"><i class="fab fa-google-plus"></i></span>
                    <span class="icon_title">Connect with Google</span>
                </a>
            </div>

            <div class="centeredText">
                <span>Or use your Email address</span>
            </div>

            <div class="action_btns">
                <div class="one_half"><a href="#" id="login_form" class="btn">Login</a></div>
                <div class="one_half last"><a href="#" id="register_form" class="btn">Sign up</a></div>
            </div>
        </div>

        <!-- Username & Password Login form -->
        <div class="user_login">
            <form action="" method="post">
                <label>Email / Username</label>
                <input name="username" type="text" id="username">
              <br>

                <label>Password</label>
                <input name="password" type="password" id="password">
              <br>

                <div class="checkbox">
                    <input id="remember" type="checkbox">
                    <label for="remember">Remember me on this computer</label>
                </div>

                <div class="action_btns">
                    <div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
                    <div class="one_half last"><button type="submit" class="btn btn_red">Login</button></div>
                </div>
            </form>

            <a href="#" class="forgot_password">Forgot password?</a>
        </div>

        <!-- Register Form -->
        <div class="user_register">
            <form action="" method="post">
                <label>Username</label>
                <input name="username" type="text" id="username">
                <br>

                <label>Email Address</label>
                <input name="email" type="email" id="email">
                <br>

                <label>Password</label>
                <input name="password" type="password" id="password">
                <br>

                <div class="checkbox">
                    <input id="send_updates" type="checkbox">
                    <label for="send_updates">Send me occasional email updates</label>
                </div>

                <div class="action_btns">
                    <div class="one_half"><a href="#" class="btn back_btn"><i class="fa fa-angle-double-left"></i> Back</a></div>
                    <div class="one_half last"><button type="submit" class="btn btn_red">Register</button></div>
                </div>
            </form>
        </div>

    </section>
  </div>

  <div class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 offset-lg-2 header-text">
          <h2>Back To Our <em>Memmories</em></h2>
          <p>“There are memories that time does not erase… Forever does not make loss forgettable, only bearable.”</p>
        </div>
      </div>
    </div>
  </div>


  <section class="photos-videos">
    <div class="container">
      <div class="row">

        <div class="col-lg-12">
          <div class="section-heading text-center">
            <h6>♥ You will forever be My Always ♥</h6>
            <h4>Our<em> Happy</em> Years</h4>
          </div>
        </div>
           {% for product in products.object_list %}
        <div class="col-lg-6">
          <div class="item">
            <div class="thumb">
              <img src="{{ product.image.url }}" alt="{{ product.name }}">

            </div>

          </div>
        </div>
{% endfor%}
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="contest-win">
    <div class="container-fluid">
      <div class="row">





        <div class="col-lg-12">
            {% if products.paginator.num_pages > 1 %}
          <ul class="pagination">
            <li><a href=""><i class=""></i></a></li>

 {% for pg in products.paginator.page_range %}
            <li><a href="?page={{pg}}" class=" {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            </li>
               {% endfor %}
            <li><a href=""><i class=""></i></a></li>
          </ul>
            {% endif %}
        </div>
      </div>
    </div>
  </section>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright © 2023 <a href="#">A ♥ R</a>  All rights reserved.

<!--          Design: <a title="CSS Templates" rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a></p>-->
        </div>
      </div>
    </div>
  </footer>

  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  <script src="{% static 'assets/js/isotope.min.js' %}"></script>
  <script src="{% static 'assets/js/owl-carousel.js' %}"></script>

  <script src="{% static 'assets/js/tabs.js' %}"></script>
  <script src="{% static 'assets/js/popup.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script><div id="lean_overlay"></div>
</body></html>

mywedding/templates/nav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>

  <header class="header-area header-sticky background-header">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="index.html" class="logo" style="color:red;font-family:cursive">
                       A <img src="{% static 'assets/images/ll.png' %}" style="width:60px;height:60px;" alt="SnapX Photography Template">
                        R
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li><a href="{% url 'myapp:index'  %} " class="active">Home</a></li>
                        <li class="has-sub">
                            <a href="javascript:void(0)">Back To Memories</a>
                            <ul class="sub-menu">
                                {% for cat in links %}
                                <li><a href="{% url 'myapp:allyear' cat.slug %}">{{cat.name}}</a></li>
<!--                                <li><a href="contest-details.html">Single Contest</a></li>-->
                                {% endfor %}
                            </ul>
                        </li>
<!--                        <li><a href="categories.html">Categories</a></li>-->
                        <li><a href="{% url 'myapp:go' %}" >♥ U</a></li>
                    </ul>

                    <a class="menu-trigger">
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
  </header>
</body>
</html>